version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - 8000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - webnet

networks:
  webnet: